dist: bionic
language: python
python:
  - "3.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y npm
  - make setup-jshint
install:
  - pip install -r requirements.txt -r requirements-dev.txt
script:
  - make lint
  - make jshint
  - make test
