version: "3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - "SEVILLA_PASSWORD=${SEVILLA_PASSWORD}"
      - "SECRET_KEY=${SECRET_KEY}"
      - "SESSION_COOKIE_SECURE=${SESSION_COOKIE_SECURE:-False}"
      - "SQLALCHEMY_DATABASE_URI=postgres://sevilla:${POSTGRES_PASSWORD}@db:5432/sevilla"
    depends_on:
      - db
  db:
    image: "postgres:11"
    environment:
      - "POSTGRES_USER=sevilla"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=sevilla"
    volumes:
      - "postgresql:/var/lib/postgresql/data"
volumes:
  postgresql:
