version: "3"
services:
  web:
    build:
      dockerfile: docker/Dockerfile
      context: ..
    ports:
      - "${SEVILLA_PORT:-8080}:8080"
    environment:
      - "SEVILLA_PASSWORD=${SEVILLA_PASSWORD:?SEVILLA_PASSWORD}"
      - "SECRET_KEY=${SEVILLA_SECRET_KEY:?SEVILLA_SECRET_KEY}"
      - "SESSION_COOKIE_SECURE=${SEVILLA_SESSION_COOKIE_SECURE:-False}"
      - "SQLALCHEMY_DATABASE_URI=postgres://sevilla:${SEVILLA_PG_PASSWORD:?SEVILLA_PG_PASSWORD}@db:5432/sevilla"
    depends_on:
      - db
  db:
    image: "postgres:11"
    environment:
      - "POSTGRES_USER=sevilla"
      - "POSTGRES_PASSWORD=${SEVILLA_PG_PASSWORD:?}"
      - "POSTGRES_DB=sevilla"
    volumes:
      - "postgresql:/var/lib/postgresql/data"
volumes:
  postgresql:
